import React, { useEffect, useState } from "react";
import { Compass, BookMarked, CreditCard, User, Lock, ChevronLeft, Search, Check } from "lucide-react";

const ink="#141311", paper="#FAF9F4", red="#C81E1E", muted="#8C897D", hairline="#E3E0D5";

const ui={
 zh:{search:"搜索",issue:"本期专题 / ISSUE 01",issueTitle:"无人观看",issueMeta:"女性独处、私人空间与观看的政治 · 共 10 篇",read:"分钟阅读",unlock:"订阅解锁",article:"正文",back:"返回",intro:"在西方视觉文化的长期传统中，女性形象经常被组织为可观看、可描述和可欲望的对象。本文的出发点不是简单要求“更多女性形象”，而是追问图像内部的关系。",body:"当人物转身、闭眼、睡眠、阅读或发呆时，她仍然处于画面之中，也仍然被观众看见；然而，她不再主动确认观看者的存在。因此，“无人观看”并非字面意义上的没有观众，而是一种方法论上的悖论。",lockedTitle:"你尚未获得进入此文本其余部分的权利",lockedText:"订阅 X-ART Lab.，解锁本篇及全部研究专题的完整正文",subscribeCta:"订阅 / 获得进入与理解的权利",membershipTitle:"订阅，获得进入与理解的权利",membershipText:"解锁全部当代艺术研究专题，含正文、参考文献与创作概念矩阵",monthly:"月度",yearly:"年度",institution:"机构",perMonth:"/ 月",perYear:"/ 年",cancel:"随时取消",yearlyNote:"相当于 €3,18 / 月",custom:"定制",institutionNote:"院校 / 图书馆 / 工作室",recommended:"推荐",benefits:["全部研究专题完整正文","可下载 PDF / 离线阅读","创作概念矩阵与实践方法附录"],subscribed:"已订阅",confirm:"确认订阅",account:"我的书房",memberStatus:"会员状态",activeMember:"X-ART Lab. 年度会员 · 有效期至 2027-08",notSubscribed:"未订阅",active:"生效中",free:"免费版",saved:"已收藏",discover:"发现",mine:"我的",subscribe:"订阅"},
 fr:{search:"Rechercher",issue:"DOSSIER DU MOIS / NUMÉRO 01",issueTitle:"Sans regard",issueMeta:"Solitude féminine, espace privé et politique du regard · 10 articles",read:"min de lecture",unlock:"Réservé aux abonnés",article:"ARTICLE",back:"Retour",intro:"Dans la longue tradition de la culture visuelle occidentale, l’image des femmes a souvent été organisée comme un objet à regarder, décrire et désirer. Il ne s’agit pas seulement de demander davantage de représentations, mais d’interroger les relations internes à l’image.",body:"Lorsqu’une figure se détourne, ferme les yeux, dort, lit ou rêvasse, elle reste visible. Pourtant, elle ne confirme plus activement la présence du regardeur. « Sans regard » est donc un paradoxe méthodologique : l’œuvre demande à être vue, tandis que son sujet peut refuser de répondre au regard.",lockedTitle:"Vous n’avez pas encore accès à la suite de ce texte",lockedText:"Abonnez-vous à X-ART Lab. pour lire cet article et tous les dossiers de recherche",subscribeCta:"S’abonner et accéder aux contenus",membershipTitle:"S’abonner pour accéder et comprendre",membershipText:"Accédez à tous les dossiers, textes, références et matrices de concepts créatifs",monthly:"Mensuel",yearly:"Annuel",institution:"Institution",perMonth:"/ mois",perYear:"/ an",cancel:"Résiliable à tout moment",yearlyNote:"Soit €3,18 / mois",custom:"Sur devis",institutionNote:"Écoles / bibliothèques / ateliers",recommended:"Conseillé",benefits:["Tous les articles de recherche","PDF téléchargeables et lecture hors ligne","Matrices conceptuelles et méthodes pratiques"],subscribed:"Abonné",confirm:"Confirmer l’abonnement",account:"Ma bibliothèque",memberStatus:"Statut de membre",activeMember:"Membre annuel X-ART Lab. · jusqu’en 08/2027",notSubscribed:"Sans abonnement",active:"Actif",free:"Gratuit",saved:"Favoris",discover:"Découvrir",mine:"Mon espace",subscribe:"S’abonner"},
 en:{search:"Search",issue:"CURRENT ISSUE / ISSUE 01",issueTitle:"Unwatched",issueMeta:"Female solitude, private space and the politics of looking · 10 articles",read:"min read",unlock:"Subscriber access",article:"ARTICLE",back:"Back",intro:"Across the long tradition of Western visual culture, women have often been organized as objects to be viewed, described and desired. The point is not simply to demand more images of women, but to question the relationships structured within the image.",body:"When a figure turns away, closes her eyes, sleeps, reads or daydreams, she remains visible. Yet she no longer confirms the viewer’s presence. “Unwatched” is therefore a methodological paradox: an artwork asks to be seen, while its subject can refuse to answer the gaze.",lockedTitle:"You do not yet have access to the rest of this text",lockedText:"Subscribe to X-ART Lab. to unlock this article and every research issue",subscribeCta:"Subscribe and access the full archive",membershipTitle:"Subscribe for access and understanding",membershipText:"Unlock every contemporary art research issue, including essays, references and creative concept matrices",monthly:"Monthly",yearly:"Yearly",institution:"Institution",perMonth:"/ month",perYear:"/ year",cancel:"Cancel anytime",yearlyNote:"Equivalent to €3.18 / month",custom:"Custom",institutionNote:"Schools / libraries / studios",recommended:"Recommended",benefits:["Complete research articles","Downloadable PDFs and offline reading","Creative concept matrices and practical methods"],subscribed:"Subscribed",confirm:"Confirm subscription",account:"My library",memberStatus:"Membership status",activeMember:"X-ART Lab. annual member · valid through 08/2027",notSubscribed:"Not subscribed",active:"Active",free:"Free",saved:"Saved",discover:"Discover",mine:"My space",subscribe:"Subscribe"}
};

const items=[
 {n:"07",tag:"UNKNOWABILITY",locked:true,minutes:12,zh:["从可见到缺席：不可知性及其悖论","不可知性不是“神秘女人”的浪漫化，而是对信息边界的坚持。"],fr:["De la visibilité à l’absence : le paradoxe de l’inconnaissable","L’inconnaissable affirme une limite de l’information, sans romantiser la « femme mystérieuse »."],en:["From Visibility to Absence: The Paradox of Unknowability","Unknowability holds a boundary around information without romanticizing the “mysterious woman.”"]},
 {n:"04",tag:"TIME",locked:true,minutes:9,zh:["独处与时间所有权：非生产性存在的政治","她没有变得更好，她只是拥有了一段不需要产生价值的时间。"],fr:["Solitude et propriété du temps","Elle possède simplement un temps qui n’a pas à produire de valeur."],en:["Solitude and the Ownership of Time","She simply owns a stretch of time that need not produce value."]},
 {n:"02",tag:"SPACE",locked:false,minutes:14,zh:["房间不是背景：Woolf、Pollock 与性别化空间","房间既可能保护主体，也可能把主体限制在私人领域。"],fr:["La chambre n’est pas un décor : Woolf, Pollock et l’espace genré","La chambre peut protéger le sujet autant qu’elle peut le confiner au domaine privé."],en:["The Room Is Not a Backdrop: Woolf, Pollock and Gendered Space","A room may protect its subject while also confining her to the private sphere."]},
 {n:"01",tag:"THE GAZE",locked:false,minutes:11,zh:["观看的结构：Berger、Mulvey 与观看权力","观看并没有消失；被撤回的是观看者理所当然获得回应的权利。"],fr:["La structure du regard : Berger, Mulvey et le pouvoir de voir","Le droit du spectateur à recevoir une réponse est retiré."],en:["The Structure of Looking: Berger, Mulvey and the Power of the Gaze","What is withdrawn is the viewer’s assumed right to a response."]}
];

const Lang=({lang,setLang})=><div className="flex gap-1" aria-label="Language">{[["zh","中文"],["fr","FR"],["en","EN"]].map(([id,label])=><button key={id} onClick={()=>setLang(id)} aria-pressed={lang===id} style={{fontSize:10,fontWeight:700,color:lang===id?paper:ink,background:lang===id?ink:"transparent",border:`1px solid ${lang===id?ink:hairline}`,borderRadius:999,padding:"5px 8px"}}>{label}</button>)}</div>;
const Eye=({children})=><div style={{color:red,fontSize:11,fontWeight:700,letterSpacing:".12em"}}>{children}</div>;

function Discover({lang,setLang,open}){
  const t=ui[lang],[query,setQuery]=useState("");
  const needle=query.trim().toLocaleLowerCase();
  const results=needle?items.filter(p=>[p.tag,...p[lang]].join(" ").toLocaleLowerCase().includes(needle)):items;
  const emptyText=lang==="zh"?"没有找到相关文章":lang==="fr"?"Aucun article trouvé":"No articles found";
  return <div className="flex flex-col h-full" style={{background:paper}}>
    <header className="px-5 pt-5 pb-4" style={{borderBottom:`1px solid ${hairline}`}}>
      <div className="flex items-start justify-between gap-3"><div><div style={{fontSize:26,fontWeight:800,color:ink}}>X-ART Lab.</div><div style={{fontSize:10,fontWeight:700,color:muted,letterSpacing:".18em"}}>CONTEMPORARY ART RESEARCH</div></div><Lang lang={lang} setLang={setLang}/></div>
      <label className="flex items-center gap-2 mt-4" style={{height:40,border:`1px solid ${hairline}`,borderRadius:999,padding:"0 14px",background:"#fff"}}>
        <Search size={15} color={muted}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search} style={{flex:1,minWidth:0,border:0,outline:0,background:"transparent",fontSize:13,color:ink}}/>
        {query&&<button onClick={()=>setQuery("")} aria-label={lang==="zh"?"清除搜索":lang==="fr"?"Effacer la recherche":"Clear search"} style={{fontSize:18,color:muted,lineHeight:1}}>×</button>}
      </label>
    </header>
    <section className="px-5 pt-5 pb-2"><Eye>{t.issue}</Eye><h1 style={{fontSize:20,fontWeight:800,marginTop:6}}>{t.issueTitle}</h1><p style={{fontSize:12,color:muted,marginTop:4}}>{t.issueMeta}</p></section>
    <main className="flex-1 overflow-y-auto px-5 pb-6">{results.map(p=><button key={p.n} onClick={()=>open(p)} className="w-full text-left" style={{padding:"16px 0",borderBottom:`1px solid ${hairline}`}}><div className="flex gap-3"><b style={{fontSize:12,color:red,minWidth:20}}>{p.n}</b><div><div style={{fontSize:10,fontWeight:700,color:muted,letterSpacing:".1em"}}>{p.tag}</div><div style={{fontSize:15,fontWeight:700,marginTop:4,lineHeight:1.4}}>{p[lang][0]}</div><div style={{fontSize:12,color:muted,marginTop:6,lineHeight:1.5}}>{p[lang][1]}</div><div className="flex gap-2" style={{marginTop:8,fontSize:11,color:muted}}><span>{p.minutes} {t.read}</span>{p.locked&&<span className="flex items-center gap-1" style={{color:red}}><Lock size={10}/>{t.unlock}</span>}</div></div></div></button>)}{results.length===0&&<div style={{padding:"40px 0",textAlign:"center",fontSize:13,color:muted}}>{emptyText}</div>}</main>
  </div>
}

function Reader({item,lang,setLang,back,toSubscribe,subscribed}){const t=ui[lang],locked=item.locked&&!subscribed;return <div className="flex flex-col h-full" style={{background:paper}}><header className="flex items-center justify-between px-5" style={{minHeight:56,borderBottom:`1px solid ${hairline}`}}><button onClick={back} aria-label={t.back}><ChevronLeft size={20}/></button><b style={{fontSize:13,letterSpacing:".06em"}}>{t.article}</b><Lang lang={lang} setLang={setLang}/></header><main className="flex-1 overflow-y-auto px-5 pt-6 pb-8"><Eye>{item.n} / {item.tag}</Eye><h1 style={{fontSize:22,fontWeight:800,marginTop:8,lineHeight:1.35}}>{item[lang][0]}</h1><div style={{fontSize:12,color:muted,marginTop:6}}>{item.minutes} {t.read}</div><hr style={{border:0,height:1,background:hairline,margin:"20px 0"}}/><p style={{fontSize:15,lineHeight:1.9}}>{item[lang][1]} {t.intro}</p>{locked?<div className="relative"><p style={{fontSize:15,lineHeight:1.9,filter:"blur(4px)",userSelect:"none"}}>{t.body}</p><div className="absolute inset-x-0 bottom-0 flex flex-col items-center text-center px-4" style={{paddingTop:48,background:`linear-gradient(180deg,transparent,${paper} 55%)`}}><Lock size={18} color={red}/><b style={{fontSize:14,marginTop:10}}>{t.lockedTitle}</b><div style={{fontSize:12,color:muted,marginTop:4}}>{t.lockedText}</div><button onClick={toSubscribe} style={{marginTop:16,background:ink,color:paper,fontSize:12,fontWeight:700,padding:"12px 22px",borderRadius:999}}>{t.subscribeCta}</button></div></div>:<p style={{fontSize:15,lineHeight:1.9}}>{t.body}</p>}</main></div>}

function Subscribe({lang,setLang,subscribed,onSubscribed}){const t=ui[lang],[selected,setSelected]=useState("yearly");const plans=[{id:"monthly",name:t.monthly,en:"MONTHLY",price:"€3,59",period:t.perMonth,note:t.cancel},{id:"yearly",name:t.yearly,en:"YEARLY",price:"€38,18",period:t.perYear,note:t.yearlyNote,rec:true},{id:"institution",name:t.institution,en:"INSTITUTION",price:t.custom,period:"",note:t.institutionNote}];return <div className="flex flex-col h-full" style={{background:paper}}><header className="px-5 pt-5 pb-4" style={{borderBottom:`1px solid ${hairline}`}}><div className="flex items-start justify-between gap-2"><div><Eye>MEMBERSHIP</Eye><h1 style={{fontSize:21,fontWeight:800,marginTop:8,lineHeight:1.3}}>{t.membershipTitle}</h1></div><Lang lang={lang} setLang={setLang}/></div><p style={{fontSize:12,color:muted,lineHeight:1.6}}>{t.membershipText}</p></header><main className="flex-1 overflow-y-auto px-5 pt-5">{plans.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} className="w-full text-left" style={{padding:16,marginBottom:12,borderRadius:12,border:`1px solid ${selected===p.id?red:hairline}`,background:selected===p.id?"#FDF1F1":"transparent"}}><div className="flex justify-between items-center gap-2"><div><div className="flex items-center gap-2"><b>{p.name}</b><small style={{color:muted}}>{p.en}</small>{p.rec&&<small style={{color:paper,background:red,padding:"2px 6px",borderRadius:4}}>{t.recommended}</small>}</div><small style={{color:muted}}>{p.note}</small></div><div><b style={{fontSize:18}}>{p.price}</b><small style={{color:muted}}>{p.period}</small>{selected===p.id&&<Check size={14} color={red}/>}</div></div></button>)}{t.benefits.map(f=><div key={f} className="flex items-center gap-2" style={{marginTop:10}}><Check size={14} color={red}/><span style={{fontSize:13}}>{f}</span></div>)}</main><footer className="px-5 pb-6 pt-3" style={{borderTop:`1px solid ${hairline}`}}><button onClick={onSubscribed} style={{width:"100%",background:subscribed?muted:ink,color:paper,fontWeight:700,padding:14,borderRadius:999}}>{subscribed?t.subscribed:t.confirm}</button></footer></div>}

function Profile({lang,setLang,subscribed}){const t=ui[lang];return <div className="h-full" style={{background:paper}}><header className="px-5 pt-5 pb-4 flex justify-between" style={{borderBottom:`1px solid ${hairline}`}}><div><Eye>ACCOUNT</Eye><h1 style={{fontSize:20,fontWeight:800,marginTop:8}}>{t.account}</h1></div><Lang lang={lang} setLang={setLang}/></header><main className="px-5 pt-5"><section style={{border:`1px solid ${hairline}`,borderRadius:12,padding:16}}><div className="flex justify-between"><div><b>{t.memberStatus}</b><div style={{fontSize:12,color:muted}}>{subscribed?t.activeMember:t.notSubscribed}</div></div><span>{subscribed?t.active:t.free}</span></div></section><h2 style={{fontSize:11,fontWeight:700,color:muted,marginTop:20}}>{t.saved}</h2>{items.slice(0,2).map(p=><div key={p.n} className="flex justify-between" style={{padding:"12px 0",borderBottom:`1px solid ${hairline}`}}><div><b style={{fontSize:13}}>{p[lang][0]}</b><div style={{fontSize:11,color:muted}}>{p.tag}</div></div><BookMarked size={16} color={muted}/></div>)}</main></div>}

function Tabs({tab,setTab,lang}){const t=ui[lang],tabs=[["discover",t.discover,Compass],["library",t.mine,User],["subscribe",t.subscribe,CreditCard]];return <nav className="flex items-center justify-around" style={{height:64,borderTop:`1px solid ${hairline}`,background:paper}}>{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className="flex flex-col items-center gap-1"><Icon size={20} color={tab===id?red:muted}/><span style={{fontSize:10,color:tab===id?red:muted,fontWeight:tab===id?700:400}}>{label}</span></button>)}</nav>}

const responsiveStyles=`
.xart-stage{min-height:100dvh;padding:0;background:#FAF9F4;align-items:stretch}
.xart-device{width:100%;height:100dvh;border:0;border-radius:0;box-shadow:none}
@media (min-width:700px){
  .xart-stage{min-height:100dvh;padding:0;background:#FAF9F4;align-items:stretch}
  .xart-device{width:100%;height:100dvh;border:0;border-radius:0;box-shadow:none}
  .xart-device header,.xart-device main,.xart-device footer{padding-left:max(32px,env(safe-area-inset-left));padding-right:max(32px,env(safe-area-inset-right))}
  .xart-device main{scrollbar-gutter:stable}
}
`;

export default function App(){const[tab,setTab]=useState("discover"),[open,setOpen]=useState(null),[subscribed,setSubscribed]=useState(false),[lang,setLang]=useState(()=>localStorage.getItem("xart-language")||"zh");useEffect(()=>{localStorage.setItem("xart-language",lang);document.documentElement.lang=lang==="zh"?"zh-CN":lang},[lang]);let screen=open?<Reader item={open} lang={lang} setLang={setLang} back={()=>setOpen(null)} toSubscribe={()=>{setOpen(null);setTab("subscribe")}} subscribed={subscribed}/>:tab==="discover"?<Discover lang={lang} setLang={setLang} open={setOpen}/>:tab==="subscribe"?<Subscribe lang={lang} setLang={setLang} subscribed={subscribed} onSubscribed={()=>setSubscribed(true)}/>:<Profile lang={lang} setLang={setLang} subscribed={subscribed}/>;return <><style>{responsiveStyles}</style><div className="xart-stage w-full flex items-center justify-center"><div className="xart-device" style={{overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{flex:1,overflow:"hidden"}}>{screen}</div>{!open&&<Tabs tab={tab} setTab={setTab} lang={lang}/>}</div></div></>}
