import React, { useEffect, useRef, useState } from "react";
import { Compass, BookMarked, CreditCard, User, Lock, ChevronLeft, Search, Check, Minus, Plus, Share2, Download, Sun, Moon, BookOpen, Pencil, X } from "lucide-react";
import Admin from "./Admin.jsx";

const ink="#141311", paper="#FAF9F4", red="#C81E1E", muted="#8C897D", hairline="#E3E0D5";

const ui={
 zh:{search:"搜索",issue:"本期专题 / ISSUE 01",issueTitle:"无人观看",issueMeta:"女性独处、私人空间与观看的政治 · 共 10 篇",read:"分钟阅读",unlock:"订阅解锁",article:"正文",back:"返回",intro:"在西方视觉文化的长期传统中，女性形象经常被组织为可观看、可描述和可欲望的对象。本文的出发点不是简单要求“更多女性形象”，而是追问图像内部的关系。",body:"当人物转身、闭眼、睡眠、阅读或发呆时，她仍然处于画面之中，也仍然被观众看见；然而，她不再主动确认观看者的存在。因此，“无人观看”并非字面意义上的没有观众，而是一种方法论上的悖论。",lockedTitle:"你尚未获得进入此文本其余部分的权利",lockedText:"订阅 X-ART Lab.，解锁本篇及全部研究专题的完整正文",subscribeCta:"订阅 / 获得进入与理解的权利",membershipTitle:"订阅，获得进入与理解的权利",membershipText:"解锁全部当代艺术研究专题，含正文、参考文献与创作概念矩阵",monthly:"月度",yearly:"年度",institution:"机构",perMonth:"/ 月",perYear:"/ 年",cancel:"随时取消",yearlyNote:"相当于 €3,18 / 月",custom:"定制",institutionNote:"院校 / 图书馆 / 工作室",recommended:"推荐",benefits:["全部研究专题完整正文","可下载 PDF / 离线阅读","创作概念矩阵与实践方法附录"],subscribed:"已订阅",confirm:"确认订阅",account:"我的书房",memberStatus:"会员状态",activeMember:"X-ART Lab. 年度会员 · 有效期至 2027-08",notSubscribed:"未订阅",active:"生效中",free:"免费版",saved:"已收藏",discover:"发现",mine:"我的",subscribe:"订阅"},
 fr:{search:"Rechercher",issue:"DOSSIER DU MOIS / NUMÉRO 01",issueTitle:"Sans regard",issueMeta:"Solitude féminine, espace privé et politique du regard · 10 articles",read:"min de lecture",unlock:"Réservé aux abonnés",article:"ARTICLE",back:"Retour",intro:"Dans la longue tradition de la culture visuelle occidentale, l’image des femmes a souvent été organisée comme un objet à regarder, décrire et désirer. Il ne s’agit pas seulement de demander davantage de représentations, mais d’interroger les relations internes à l’image.",body:"Lorsqu’une figure se détourne, ferme les yeux, dort, lit ou rêvasse, elle reste visible. Pourtant, elle ne confirme plus activement la présence du regardeur. « Sans regard » est donc un paradoxe méthodologique : l’œuvre demande à être vue, tandis que son sujet peut refuser de répondre au regard.",lockedTitle:"Vous n’avez pas encore accès à la suite de ce texte",lockedText:"Abonnez-vous à X-ART Lab. pour lire cet article et tous les dossiers de recherche",subscribeCta:"S’abonner et accéder aux contenus",membershipTitle:"S’abonner pour accéder et comprendre",membershipText:"Accédez à tous les dossiers, textes, références et matrices de concepts créatifs",monthly:"Mensuel",yearly:"Annuel",institution:"Institution",perMonth:"/ mois",perYear:"/ an",cancel:"Résiliable à tout moment",yearlyNote:"Soit €3,18 / mois",custom:"Sur devis",institutionNote:"Écoles / bibliothèques / ateliers",recommended:"Conseillé",benefits:["Tous les articles de recherche","PDF téléchargeables et lecture hors ligne","Matrices conceptuelles et méthodes pratiques"],subscribed:"Abonné",confirm:"Confirmer l’abonnement",account:"Ma bibliothèque",memberStatus:"Statut de membre",activeMember:"Membre annuel X-ART Lab. · jusqu’en 08/2027",notSubscribed:"Sans abonnement",active:"Actif",free:"Gratuit",saved:"Favoris",discover:"Découvrir",mine:"Mon espace",subscribe:"S’abonner"},
 en:{search:"Search",issue:"CURRENT ISSUE / ISSUE 01",issueTitle:"Unwatched",issueMeta:"Female solitude, private space and the politics of looking · 10 articles",read:"min read",unlock:"Subscriber access",article:"ARTICLE",back:"Back",intro:"Across the long tradition of Western visual culture, women have often been organized as objects to be viewed, described and desired. The point is not simply to demand more images of women, but to question the relationships structured within the image.",body:"When a figure turns away, closes her eyes, sleeps, reads or daydreams, she remains visible. Yet she no longer confirms the viewer’s presence. “Unwatched” is therefore a methodological paradox: an artwork asks to be seen, while its subject can refuse to answer the gaze.",lockedTitle:"You do not yet have access to the rest of this text",lockedText:"Subscribe to X-ART Lab. to unlock this article and every research issue",subscribeCta:"Subscribe and access the full archive",membershipTitle:"Subscribe for access and understanding",membershipText:"Unlock every contemporary art research issue, including essays, references and creative concept matrices",monthly:"Monthly",yearly:"Yearly",institution:"Institution",perMonth:"/ month",perYear:"/ year",cancel:"Cancel anytime",yearlyNote:"Equivalent to €3.18 / month",custom:"Custom",institutionNote:"Schools / libraries / studios",recommended:"Recommended",benefits:["Complete research articles","Downloadable PDFs and offline reading","Creative concept matrices and practical methods"],subscribed:"Subscribed",confirm:"Confirm subscription",account:"My library",memberStatus:"Membership status",activeMember:"X-ART Lab. annual member · valid through 08/2027",notSubscribed:"Not subscribed",active:"Active",free:"Free",saved:"Saved",discover:"Discover",mine:"My space",subscribe:"Subscribe"}
};

const fallbackItems=[
 {n:"07",tag:"UNKNOWABILITY",locked:true,minutes:12,zh:["从可见到缺席：不可知性及其悖论","不可知性不是“神秘女人”的浪漫化，而是对信息边界的坚持。"],fr:["De la visibilité à l’absence : le paradoxe de l’inconnaissable","L’inconnaissable affirme une limite de l’information, sans romantiser la « femme mystérieuse »."],en:["From Visibility to Absence: The Paradox of Unknowability","Unknowability holds a boundary around information without romanticizing the “mysterious woman.”"]},
 {n:"04",tag:"TIME",locked:true,minutes:9,zh:["独处与时间所有权：非生产性存在的政治","她没有变得更好，她只是拥有了一段不需要产生价值的时间。"],fr:["Solitude et propriété du temps","Elle possède simplement un temps qui n’a pas à produire de valeur."],en:["Solitude and the Ownership of Time","She simply owns a stretch of time that need not produce value."]},
 {n:"02",tag:"SPACE",locked:false,minutes:14,zh:["房间不是背景：Woolf、Pollock 与性别化空间","房间既可能保护主体，也可能把主体限制在私人领域。"],fr:["La chambre n’est pas un décor : Woolf, Pollock et l’espace genré","La chambre peut protéger le sujet autant qu’elle peut le confiner au domaine privé."],en:["The Room Is Not a Backdrop: Woolf, Pollock and Gendered Space","A room may protect its subject while also confining her to the private sphere."]},
 {n:"01",tag:"THE GAZE",locked:false,minutes:11,zh:["观看的结构：Berger、Mulvey 与观看权力","观看并没有消失；被撤回的是观看者理所当然获得回应的权利。"],fr:["La structure du regard : Berger, Mulvey et le pouvoir de voir","Le droit du spectateur à recevoir une réponse est retiré."],en:["The Structure of Looking: Berger, Mulvey and the Power of the Gaze","What is withdrawn is the viewer’s assumed right to a response."]}
];

const Lang=({lang,setLang})=><div className="flex gap-1" aria-label="Language">{[["zh","中文"],["fr","FR"],["en","EN"]].map(([id,label])=><button key={id} onClick={()=>setLang(id)} aria-pressed={lang===id} style={{fontSize:10,fontWeight:700,color:lang===id?paper:ink,background:lang===id?ink:"transparent",border:`1px solid ${lang===id?ink:hairline}`,borderRadius:999,padding:"5px 8px"}}>{label}</button>)}</div>;
const Eye=({children})=><div style={{color:red,fontSize:11,fontWeight:700,letterSpacing:".12em"}}>{children}</div>;
const readerInlineHtml=text=>String(text).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\[font=(sans|serif|mono)\]([\s\S]*?)\[\/font\]/g,(_,font,value)=>`<span style="font-family:${font==="serif"?"Georgia,serif":font==="mono"?"ui-monospace,monospace":"Arial,sans-serif"}">${value}</span>`).replace(/\[size=(12|14|16|18|24|32)\]([\s\S]*?)\[\/size\]/g,'<span style="font-size:$1px">$2</span>').replace(/\[color=(#[0-9a-fA-F]{6})\]([\s\S]*?)\[\/color\]/g,'<span style="color:$1">$2</span>').replace(/\[bg=(#[0-9a-fA-F]{6})\]([\s\S]*?)\[\/bg\]/g,'<span style="background-color:$1;padding:.08em .18em">$2</span>').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/_([^_]+)_/g,"<em>$1</em>");
function RichText({text="",blurred=false}){const parts=text.split(/(!\[[^\]]*\]\([^)]+\)|\n\s*\n)/g).filter(value=>value&&!/^\n+$/.test(value));return <div className="richtext" style={{filter:blurred?"blur(4px)":"none",userSelect:blurred?"none":"auto"}}>{parts.map((part,index)=>{const image=part.match(/^!\[([^\]]*)\]\((.+)\)$/s);if(image)return <figure key={index}><img src={image[2]} alt={image[1]}/>{image[1]&&image[1]!=="image"&&<figcaption>{image[1]}</figcaption>}</figure>;const value=part.trim();if(/^---+$/.test(value))return <hr key={index}/>;if(value.startsWith("## "))return <h3 key={index} dangerouslySetInnerHTML={{__html:readerInlineHtml(value.slice(3))}}/>;if(value.startsWith("# "))return <h2 key={index} dangerouslySetInnerHTML={{__html:readerInlineHtml(value.slice(2))}}/>;if(value.startsWith("> "))return <blockquote key={index} dangerouslySetInnerHTML={{__html:readerInlineHtml(value.slice(2))}}/>;const lines=value.split("\n"),unordered=lines.every(line=>line.startsWith("- ")),ordered=lines.every(line=>/^\d+\. /.test(line));if(unordered)return <ul key={index}>{lines.map((line,i)=><li key={i} dangerouslySetInnerHTML={{__html:readerInlineHtml(line.slice(2))}}/>)}</ul>;if(ordered)return <ol key={index}>{lines.map((line,i)=><li key={i} dangerouslySetInnerHTML={{__html:readerInlineHtml(line.replace(/^\d+\. /,""))}}/>)}</ol>;return <p key={index} dangerouslySetInnerHTML={{__html:readerInlineHtml(value).replace(/\n/g,"<br>")}}/>})}</div>}

function Discover({lang,setLang,open,items}){
  const t=ui[lang],[query,setQuery]=useState("");
  const needle=query.trim().toLocaleLowerCase(),localized=items.filter(p=>!p.language||p.language==="all"||p.language===lang);
  const results=needle?localized.filter(p=>[p.tag,...(p[lang]||[])].join(" ").toLocaleLowerCase().includes(needle)):localized;
  const emptyText=lang==="zh"?"没有找到相关文章":lang==="fr"?"Aucun article trouvé":"No articles found";
  return <div className="flex flex-col h-full" style={{background:paper}}>
    <header className="px-5 pt-5 pb-4" style={{borderBottom:`1px solid ${hairline}`}}>
      <div className="flex items-start justify-between gap-3"><div><div style={{fontSize:26,fontWeight:800,color:ink}}>X-ART Lab.</div><div style={{fontSize:10,fontWeight:700,color:muted,letterSpacing:".18em"}}>CONTEMPORARY ART RESEARCH</div></div><Lang lang={lang} setLang={setLang}/></div>
      <label className="flex items-center gap-2 mt-4" style={{height:40,border:`1px solid ${hairline}`,borderRadius:999,padding:"0 14px",background:"#fff"}}>
        <Search size={15} color={muted}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search} style={{flex:1,minWidth:0,border:0,outline:0,background:"transparent",fontSize:13,color:ink}}/>
        {query&&<button onClick={()=>setQuery("")} aria-label={lang==="zh"?"清除搜索":lang==="fr"?"Effacer la recherche":"Clear search"} style={{fontSize:18,color:muted,lineHeight:1}}>×</button>}
      </label>
    </header>
    <main className="flex-1 overflow-y-auto px-5 pb-6">{results.map(p=><button key={p.id||p.n} onClick={()=>open(p)} className="w-full text-left" style={{padding:"16px 0",borderBottom:`1px solid ${hairline}`}}>{p.cover_image&&<img src={p.cover_image} alt="" style={{width:"100%",height:180,objectFit:"cover",borderRadius:8,marginBottom:14}}/>}<div className="flex gap-3"><b style={{fontSize:12,color:red,minWidth:20}}>{p.n}</b><div><div style={{fontSize:10,fontWeight:700,color:muted,letterSpacing:".1em"}}>{p.tag}</div><div style={{fontSize:15,fontWeight:700,marginTop:4,lineHeight:1.4}}>{p[lang][0]}</div><div style={{fontSize:12,color:muted,marginTop:6,lineHeight:1.5}}>{p[lang][1]}</div><div className="flex gap-2" style={{marginTop:8,fontSize:11,color:muted}}><span>{p.minutes} {t.read}</span>{p.locked&&<span className="flex items-center gap-1" style={{color:red}}><Lock size={10}/>{t.unlock}</span>}</div></div></div></button>)}{results.length===0&&<div style={{padding:"40px 0",textAlign:"center",fontSize:13,color:muted}}>{emptyText}</div>}</main>
  </div>
}

function Reader({item,lang,setLang,back,toSubscribe,subscribed}){
  const t=ui[lang],locked=item.locked&&!subscribed,articleBody=item.content?.[lang]||t.body,scrollRef=useRef(null);
  const[fontScale,setFontScale]=useState(()=>Number(localStorage.getItem("xart-reader-scale"))||1),[progress,setProgress]=useState(0),[notice,setNotice]=useState(""),[theme,setTheme]=useState(()=>localStorage.getItem("xart-reader-theme")||"light"),[annotating,setAnnotating]=useState(false),[note,setNote]=useState("");
  const labels=lang==="zh"?{smaller:"缩小字号",larger:"放大字号",share:"分享",download:"下载 PDF",copied:"链接已复制",light:"日间模式",night:"夜间模式",eink:"墨水屏模式",annotate:"批注模式",notes:"文章批注",notePlaceholder:"在这里记录你的想法、引用和研究线索……",saved:"批注自动保存在此设备"}:lang==="fr"?{smaller:"Réduire le texte",larger:"Agrandir le texte",share:"Partager",download:"Télécharger le PDF",copied:"Lien copié",light:"Mode clair",night:"Mode nuit",eink:"Mode e-ink",annotate:"Annotations",notes:"Notes de lecture",notePlaceholder:"Notez ici vos idées, citations et pistes de recherche…",saved:"Notes enregistrées automatiquement sur cet appareil"}:{smaller:"Decrease text size",larger:"Increase text size",share:"Share",download:"Download PDF",copied:"Link copied",light:"Light mode",night:"Night mode",eink:"E-ink mode",annotate:"Annotation mode",notes:"Reading notes",notePlaceholder:"Record ideas, quotations and research leads here…",saved:"Notes are saved automatically on this device"};
  const noteKey=`xart-note-${item.id||item.n}-${lang}`;
  useEffect(()=>{setNote(localStorage.getItem(noteKey)||"")},[noteKey]);
  const resize=amount=>setFontScale(current=>{const next=Math.max(.85,Math.min(1.3,Math.round((current+amount)*100)/100));localStorage.setItem("xart-reader-scale",next);return next});
  const changeTheme=next=>{setTheme(next);localStorage.setItem("xart-reader-theme",next)};
  const changeNote=value=>{setNote(value);localStorage.setItem(noteKey,value)};
  const updateProgress=event=>{const element=event.currentTarget,max=element.scrollHeight-element.clientHeight;setProgress(max>0?Math.min(100,Math.max(0,element.scrollTop/max*100)):0)};
  const share=async()=>{const data={title:item[lang][0],text:item[lang][1],url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);setNotice(labels.copied);setTimeout(()=>setNotice(""),1800)}}catch{}};
  return <article className={`swiss-reader swiss-theme-${theme}`}>
    <header className="swiss-reader-header">
      <button onClick={back} aria-label={t.back}><ChevronLeft size={20}/><span>{t.back}</span></button>
      <div className="swiss-reader-brand"><b>X-ART LAB</b><small>CONTEMPORARY ART RESEARCH</small></div>
      <Lang lang={lang} setLang={setLang}/>
    </header>
    <div className="swiss-reader-toolbar">
      <div className="swiss-progress" aria-hidden="true"><i style={{width:`${progress}%`}}/></div>
      <div className="swiss-tool-group"><button onClick={()=>resize(-.1)} aria-label={labels.smaller} title={labels.smaller}><Minus size={15}/><span>A</span></button><b>{Math.round(fontScale*100)}%</b><button onClick={()=>resize(.1)} aria-label={labels.larger} title={labels.larger}><Plus size={15}/><span>A</span></button></div>
      <div className="swiss-tool-group swiss-theme-tools"><button className={theme==="light"?"active":""} onClick={()=>changeTheme("light")} aria-label={labels.light} title={labels.light}><Sun size={15}/></button><button className={theme==="night"?"active":""} onClick={()=>changeTheme("night")} aria-label={labels.night} title={labels.night}><Moon size={15}/></button><button className={theme==="eink"?"active":""} onClick={()=>changeTheme("eink")} aria-label={labels.eink} title={labels.eink}><BookOpen size={15}/></button></div>
      <div className="swiss-tool-group swiss-tool-actions"><button className={annotating?"active":""} onClick={()=>setAnnotating(value=>!value)} aria-label={labels.annotate} title={labels.annotate}><Pencil size={15}/><span>{labels.annotate}</span></button><button onClick={share} aria-label={labels.share} title={labels.share}><Share2 size={15}/><span>{labels.share}</span></button><button onClick={()=>locked?toSubscribe():downloadArticle(item,lang)} aria-label={locked?t.unlock:labels.download} title={locked?t.unlock:labels.download}>{locked?<Lock size={14}/>:<Download size={15}/>}<span>PDF</span></button></div>
      {notice&&<div className="swiss-reader-notice" role="status">{notice}</div>}
    </div>
    {annotating&&<aside className="swiss-note-panel"><div><b>{labels.notes}</b><button onClick={()=>setAnnotating(false)} aria-label="Close"><X size={16}/></button></div><textarea value={note} onChange={event=>changeNote(event.target.value)} placeholder={labels.notePlaceholder}/><small>{labels.saved}</small></aside>}
    <main ref={scrollRef} onScroll={updateProgress} className="swiss-reader-scroll" style={{"--reader-body-size":`${17*fontScale}px`,"--reader-summary-size":`${24*fontScale}px`}}>
      <section className="swiss-reader-hero">
        <div className="swiss-red-rule"/>
        <div className="swiss-meta"><b>{item.n}</b><span>{item.tag}</span><span>{item.minutes} {t.read}</span></div>
        <h1>{item[lang][0]}</h1>
      </section>
      {item.cover_image&&<img className="swiss-cover" src={item.cover_image} alt=""/>}
      <section className="swiss-reader-body">
        <p className="swiss-summary">{item[lang][1]}</p>
        <div className="swiss-body-rule"/>
        {locked?<div className="relative"><RichText text={articleBody} blurred/><div className="swiss-lock"><Lock size={20} color={red}/><b>{t.lockedTitle}</b><span>{t.lockedText}</span><button onClick={toSubscribe}>{t.subscribeCta}</button></div></div>:<RichText text={articleBody}/>}
        <footer className="swiss-article-footer"><img src="https://zhou-xing.com/logo.png" alt="官网 Logo"/><div className="swiss-footer-copy"><span className="swiss-footer-title">{item[lang][0]}</span><span className="swiss-footer-site">ZHOU-XING.COM</span></div></footer>
      </section>
    </main>
  </article>
}

function Subscribe({lang,setLang,subscribed}){
  const t=ui[lang],[selected,setSelected]=useState("yearly"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const plans=[{id:"monthly",name:t.monthly,en:"MONTHLY",price:"€3,59",period:t.perMonth,note:t.cancel},{id:"yearly",name:t.yearly,en:"YEARLY",price:"€38,18",period:t.perYear,note:t.yearlyNote,rec:true},{id:"institution",name:t.institution,en:"INSTITUTION",price:t.custom,period:"",note:t.institutionNote}];
  const checkout=async()=>{if(subscribed)return;if(selected==="institution"){setError(lang==="zh"?"机构订阅请联系 X-ART Lab。":lang==="fr"?"Contactez X-ART Lab pour un abonnement institutionnel.":"Contact X-ART Lab for an institutional plan.");return}setBusy(true);setError("");try{const response=await fetch("/api/create-checkout-session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan:selected})});const data=await response.json();if(!response.ok||!data.url)throw new Error(data.error||"Stripe error");location.href=data.url}catch(e){setError(e.message)}finally{setBusy(false)}};
  const payLabel=busy?(lang==="zh"?"正在连接 Stripe…":lang==="fr"?"Connexion à Stripe…":"Connecting to Stripe…"):(lang==="zh"?"前往 Stripe 安全支付":lang==="fr"?"Payer avec Stripe":"Continue to secure Stripe payment");
  return <div className="flex flex-col h-full" style={{background:paper}}><header className="px-5 pt-5 pb-4" style={{borderBottom:`1px solid ${hairline}`}}><div className="flex items-start justify-between gap-2"><div><Eye>MEMBERSHIP</Eye><h1 style={{fontSize:21,fontWeight:800,marginTop:8,lineHeight:1.3}}>{t.membershipTitle}</h1></div><Lang lang={lang} setLang={setLang}/></div><p style={{fontSize:12,color:muted,lineHeight:1.6}}>{t.membershipText}</p></header><main className="flex-1 overflow-y-auto px-5 pt-5">{plans.map(p=><button key={p.id} onClick={()=>{setSelected(p.id);setError("")}} className="w-full text-left" style={{padding:16,marginBottom:12,borderRadius:12,border:`1px solid ${selected===p.id?red:hairline}`,background:selected===p.id?"#FDF1F1":"transparent"}}><div className="flex justify-between items-center gap-2"><div><div className="flex items-center gap-2"><b>{p.name}</b><small style={{color:muted}}>{p.en}</small>{p.rec&&<small style={{color:paper,background:red,padding:"2px 6px",borderRadius:4}}>{t.recommended}</small>}</div><small style={{color:muted}}>{p.note}</small></div><div><b style={{fontSize:18}}>{p.price}</b><small style={{color:muted}}>{p.period}</small>{selected===p.id&&<Check size={14} color={red}/>}</div></div></button>)}{t.benefits.map(f=><div key={f} className="flex items-center gap-2" style={{marginTop:10}}><Check size={14} color={red}/><span style={{fontSize:13}}>{f}</span></div>)}</main><footer className="px-5 pb-6 pt-3" style={{borderTop:`1px solid ${hairline}`}}>{error&&<p style={{fontSize:12,color:red,textAlign:"center",margin:"0 0 8px"}}>{error}</p>}<button disabled={busy||subscribed} onClick={checkout} style={{width:"100%",border:0,background:subscribed?muted:ink,color:paper,fontWeight:700,padding:14,borderRadius:999}}>{subscribed?t.subscribed:payLabel}</button></footer></div>
}

const loadPdfImage=src=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
function wrapCanvasText(context,text,maxWidth){const lines=[];for(const paragraph of String(text||"").split(/\n/)){if(!paragraph){lines.push("");continue}let line="";for(const character of paragraph){const next=line+character;if(context.measureText(next).width>maxWidth&&line){lines.push(line);line=character}else line=next}if(line)lines.push(line)}return lines}
function blackLogoCanvas(image){const canvas=document.createElement("canvas");canvas.width=image.naturalWidth||image.width;canvas.height=image.naturalHeight||image.height;const context=canvas.getContext("2d",{willReadFrequently:true});context.drawImage(image,0,0);const pixels=context.getImageData(0,0,canvas.width,canvas.height);for(let index=0;index<pixels.data.length;index+=4){const alpha=pixels.data[index+3],lightness=(pixels.data[index]+pixels.data[index+1]+pixels.data[index+2])/3;if(!alpha)continue;if(lightness>245){pixels.data[index+3]=0;continue}pixels.data[index]=0;pixels.data[index+1]=0;pixels.data[index+2]=0}context.putImageData(pixels,0,0);return canvas}
const cleanPdfInline=text=>String(text||"").replace(/\[(?:font|size|color|bg)=[^\]]+\]|\[\/(?:font|size|color|bg)\]/g,"").replace(/\[([^\]]+)\]\([^)]+\)/g,"$1").replace(/\*\*([^*]+)\*\*/g,"$1").replace(/\*([^*]+)\*/g,"$1").replace(/_([^_]+)_/g,"$1");

async function downloadArticle(item,lang){
  const {jsPDF}=await import("jspdf");
  const articleTitle=item[lang][0],summary=item[lang][1],body=item.content?.[lang]||"";
  const width=1240,height=1754,left=112,right=102,contentWidth=width-left-right,footerTop=1515,pages=[];
  let canvas,context,y;
  const newPage=()=>{canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;context=canvas.getContext("2d");context.fillStyle="#FFFFFF";context.fillRect(0,0,width,height);context.fillStyle="#111111";y=112;pages.push({canvas,context})};
  const ensure=space=>{if(y+space>footerTop){newPage()}};
  const drawText=(text,{font="30px Arial",color="#111111",lineHeight=47,spaceAfter=22,maxWidth=contentWidth,x=left}={})=>{context.font=font;const lines=wrapCanvasText(context,text,maxWidth);for(const line of lines){ensure(lineHeight);context.font=font;context.fillStyle=color;context.fillText(line,x,y);y+=lineHeight}y+=spaceAfter};
  const drawRule=()=>{ensure(42);context.strokeStyle="#B8B8B8";context.lineWidth=2;context.beginPath();context.moveTo(left,y+10);context.lineTo(width-right,y+10);context.stroke();y+=42};
  const drawRichBlock=block=>{const value=block.trim();if(!value)return;if(/^---+$/.test(value)){drawRule();return}if(value.startsWith("## ")){drawText(cleanPdfInline(value.slice(3)),{font:"700 39px Arial",lineHeight:48,spaceAfter:24,maxWidth:contentWidth*.83});return}if(value.startsWith("# ")){drawText(cleanPdfInline(value.slice(2)),{font:"700 45px Arial",lineHeight:54,spaceAfter:28,maxWidth:contentWidth*.83});return}if(/^\*\*[^\n]+\*\*$/.test(value)){drawText(cleanPdfInline(value),{font:"700 37px Arial",lineHeight:48,spaceAfter:28,maxWidth:contentWidth*.83});return}if(value.startsWith("> ")){ensure(30);context.fillStyle="#C81E1E";context.fillRect(left,y-4,6,Math.max(54,wrapCanvasText(context,cleanPdfInline(value.slice(2)),contentWidth*.76).length*43));drawText(cleanPdfInline(value.slice(2)),{font:"italic 27px Georgia",color:"#333333",lineHeight:43,spaceAfter:30,maxWidth:contentWidth*.76,x:left+24});return}const lines=value.split("\n");if(lines.every(line=>line.startsWith("- "))){for(const line of lines)drawText("•  "+cleanPdfInline(line.slice(2)),{font:"27px Arial",lineHeight:42,spaceAfter:6,maxWidth:contentWidth*.8,x:left+12});y+=14;return}if(lines.every(line=>/^\d+\. /.test(line))){for(const line of lines)drawText(cleanPdfInline(line),{font:"27px Arial",lineHeight:42,spaceAfter:6,maxWidth:contentWidth*.8,x:left+12});y+=14;return}drawText(cleanPdfInline(value),{font:"29px Arial",lineHeight:47,spaceAfter:26,maxWidth:contentWidth*.83})};
  const drawImage=async src=>{if(!src)return;try{const image=await loadPdfImage(src),scale=Math.min(contentWidth/image.width,600/image.height),w=image.width*scale,h=image.height*scale;ensure(h+34);context.fillStyle="#FFFFFF";context.fillRect(left-2,y-2,w+4,h+4);context.drawImage(image,left,y,w,h);y+=h+34}catch{}};
  newPage();
  context.fillStyle="#C81E1E";context.fillRect(left,82,84,8);
  context.font="700 20px Arial";context.fillStyle="#111111";context.fillText("X-ART LAB",left,132);context.font="18px Arial";context.fillStyle="#666666";context.fillText("CONTEMPORARY ART RESEARCH",left,163);
  context.textAlign="right";context.font="bold 66px Arial";context.fillStyle="#C81E1E";context.fillText(item.n||"01",width-right,150);context.textAlign="left";y=252;
  // Use an explicit bold face for the PDF title. Numeric font weights are not
  // rendered consistently by every browser canvas/PDF combination.
  drawText(articleTitle,{font:"bold 58px Arial",lineHeight:70,spaceAfter:28,maxWidth:contentWidth*.83});
  context.strokeStyle="#111111";context.lineWidth=3;context.beginPath();context.moveTo(left,y);context.lineTo(width-right,y);context.stroke();y+=34;
  context.font="19px Arial";context.fillStyle="#666666";context.fillText(`${item.tag}  /  ${item.minutes} MIN`,left,y);y+=58;
  await drawImage(item.cover_image);
  drawText(summary,{font:"italic 29px Arial",color:"#444444",lineHeight:45,spaceAfter:38,maxWidth:contentWidth*.83});
  const parts=body.split(/(!\[[^\]]*\]\([^)]+\)|\n\s*\n)/g).filter(part=>part&&!/^\n+$/.test(part));
  for(let partIndex=0;partIndex<parts.length;partIndex++){
    const part=parts[partIndex],image=part.match(/^!\[([^\]]*)\]\((.+)\)$/s);
    const nextText=cleanPdfInline(parts[partIndex+1]||"").replace(/^#{1,2}\s*/,"").trim();
    const beginsSources=/^(?:学术来源|来源与延伸阅读|来源|critical source|further reading|sources?|source critique|références?)/i.test(nextText);
    // A Markdown divider immediately before the bibliography creates an
    // unnecessary long grey rule. The section heading already separates it.
    if(/^\s*---+\s*$/.test(part)&&beginsSources)continue;
    if(image)await drawImage(image[2]);else drawRichBlock(part)
  }
  let logo=null;try{logo=blackLogoCanvas(await loadPdfImage(`/api/site-logo?v=${Date.now()}`))}catch{}
  pages.forEach(({context:ctx},index)=>{
    ctx.fillStyle="#FFFFFF";ctx.fillRect(0,footerTop-8,width,height-footerTop+8);
    // Keep the running footer rule on interior pages, but omit it from the
    // final page so a long isolated grey line never appears at the end.
    if(index<pages.length-1){ctx.strokeStyle="#111111";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(left,footerTop+12);ctx.lineTo(width-right,footerTop+12);ctx.stroke()}
    const logoTop=footerTop+34,logoHeight=36,logoWidth=logo?Math.min(145,logo.width*(logoHeight/logo.height)):0,copyLeft=left+(logoWidth?logoWidth+16:0);
    if(logo)ctx.drawImage(logo,left,logoTop,logoWidth,logoHeight);
    ctx.textAlign="right";ctx.font="700 14px Arial";ctx.fillStyle="#C81E1E";ctx.fillText(String(index+1).padStart(2,"0")+" / "+String(pages.length).padStart(2,"0"),width-right,footerTop+49);
    ctx.textAlign="left";ctx.font="700 16px Arial";ctx.fillStyle="#111111";const footerTitleLines=wrapCanvasText(ctx,articleTitle,width-right-copyLeft-105);footerTitleLines.forEach((line,lineIndex)=>ctx.fillText(line,copyLeft,footerTop+47+lineIndex*21));
    ctx.font="700 12px Arial";ctx.fillStyle="#555555";ctx.fillText("ZHOU-XING.COM",copyLeft,footerTop+47+footerTitleLines.length*21+3);
  });
  const pdf=new jsPDF({orientation:"portrait",unit:"pt",format:"a4",compress:true});
  pages.forEach(({canvas:page},index)=>{if(index)pdf.addPage();pdf.addImage(page.toDataURL("image/jpeg",.9),"JPEG",0,0,595.28,841.89,undefined,"FAST")});
  pdf.save(`${articleTitle.replace(/[\\/:*?"<>|]/g,"-")}.pdf`);
}

function Profile({lang,setLang,subscribed,items,onRead}){const t=ui[lang],readLabel=lang==="zh"?"阅读":lang==="fr"?"Lire":"Read",downloadLabel=lang==="zh"?"下载":lang==="fr"?"Télécharger":"Download",localized=items.filter(p=>!p.language||p.language==="all"||p.language===lang);return <div className="h-full" style={{background:paper}}><header className="px-5 pt-5 pb-4 flex justify-between" style={{borderBottom:`1px solid ${hairline}`}}><div><Eye>ACCOUNT</Eye><h1 style={{fontSize:20,fontWeight:800,marginTop:8}}>{t.account}</h1></div><Lang lang={lang} setLang={setLang}/></header><main className="px-5 pt-5 overflow-y-auto" style={{height:"calc(100% - 92px)"}}><section style={{border:`1px solid ${hairline}`,borderRadius:12,padding:16}}><div className="flex justify-between"><div><b>{t.memberStatus}</b><div style={{fontSize:12,color:muted}}>{subscribed?t.activeMember:t.notSubscribed}</div></div><span>{subscribed?t.active:t.free}</span></div></section><h2 style={{fontSize:11,fontWeight:700,color:muted,marginTop:20}}>{t.saved}</h2>{localized.slice(0,2).map(p=><article key={p.id||p.n} style={{padding:"14px 0",borderBottom:`1px solid ${hairline}`}}><div className="flex justify-between gap-3"><div><b style={{fontSize:13}}>{p[lang][0]}</b><div style={{fontSize:11,color:muted,marginTop:3}}>{p.tag}</div></div><BookMarked size={16} color={muted}/></div><div className="flex gap-2" style={{marginTop:10}}><button onClick={()=>onRead(p)} style={{border:0,borderRadius:999,background:ink,color:paper,padding:"8px 16px",fontSize:12,fontWeight:700}}>{readLabel}</button><button onClick={()=>downloadArticle(p,lang)} style={{border:`1px solid ${hairline}`,borderRadius:999,background:"transparent",color:ink,padding:"8px 16px",fontSize:12,fontWeight:700}}>{downloadLabel}</button></div></article>)}</main></div>}

function Tabs({tab,setTab,lang}){const t=ui[lang],tabs=[["discover",t.discover,Compass],["library",t.mine,User],["subscribe",t.subscribe,CreditCard]];return <nav className="flex items-center justify-around" style={{height:64,borderTop:`1px solid ${hairline}`,background:paper}}>{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className="flex flex-col items-center gap-1"><Icon size={20} color={tab===id?red:muted}/><span style={{fontSize:10,color:tab===id?red:muted,fontWeight:tab===id?700:400}}>{label}</span></button>)}</nav>}

const responsiveStyles=`
@keyframes xartSplashExit{0%,68%{opacity:1}100%{opacity:0;visibility:hidden}}
@keyframes xartSplashLogo{0%{opacity:0;transform:scale(.96)}22%,72%{opacity:1;transform:scale(1)}100%{opacity:0;transform:scale(1.015)}}
.xart-splash{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;width:100vw;height:100dvh;background:#000;animation:xartSplashExit 1.8s ease forwards;pointer-events:none}
.xart-splash img{display:block;width:min(46vw,260px);max-height:22vh;object-fit:contain;filter:grayscale(1) brightness(0) invert(1);animation:xartSplashLogo 1.8s ease forwards}
.xart-stage{min-height:100dvh;padding:0;background:#FAF9F4;align-items:stretch}
.xart-device{width:100%;height:100dvh;border:0;border-radius:0;box-shadow:none}
.swiss-reader{--reader-bg:#fff;--reader-fg:#111;--reader-muted:#777;--reader-line:#ddd;--reader-accent:#c81e1e;height:100%;display:flex;flex-direction:column;background:var(--reader-bg);color:var(--reader-fg)}.swiss-theme-night{--reader-bg:#11110f;--reader-fg:#efede6;--reader-muted:#aaa79f;--reader-line:#3b3934;--reader-accent:#ef5b52}.swiss-theme-eink{--reader-bg:#dedfd8;--reader-fg:#111;--reader-muted:#4c4d48;--reader-line:#8d8e87;--reader-accent:#111}
.swiss-reader-header{min-height:72px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:0 clamp(18px,4vw,52px);border-bottom:1px solid var(--reader-fg);background:var(--reader-bg)}
.swiss-reader-header>button{display:flex;align-items:center;gap:5px;justify-self:start;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.08em}
.swiss-reader-header>.flex{justify-self:end}.swiss-reader-brand{text-align:center;line-height:1.05}.swiss-reader-brand b{display:block;font-size:15px;letter-spacing:.04em}.swiss-reader-brand small{font-size:7px;letter-spacing:.18em;color:var(--reader-muted)}
.swiss-reader-scroll{flex:1;overflow-y:auto;background:var(--reader-bg)}
.swiss-reader-toolbar{position:relative;min-height:46px;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:0 clamp(18px,4vw,52px);border-bottom:1px solid var(--reader-line);background:var(--reader-bg)}.swiss-progress{position:absolute;left:0;right:0;bottom:-1px;height:2px;background:transparent}.swiss-progress i{display:block;height:100%;background:var(--reader-accent);transition:width .12s linear}.swiss-tool-group{display:flex;align-items:center;gap:5px}.swiss-tool-group button{height:30px;display:flex;align-items:center;gap:3px;padding:0 8px;border:1px solid var(--reader-line);background:var(--reader-bg);color:var(--reader-fg);font-size:10px;font-weight:700;letter-spacing:.04em}.swiss-tool-group button:hover,.swiss-tool-group button.active{border-color:var(--reader-fg);background:var(--reader-fg);color:var(--reader-bg)}.swiss-tool-group>b{min-width:38px;text-align:center;font-size:9px;color:var(--reader-muted)}.swiss-tool-actions{margin-left:auto}.swiss-reader-notice{position:absolute;right:clamp(18px,4vw,52px);top:52px;z-index:5;padding:8px 12px;background:var(--reader-fg);color:var(--reader-bg);font-size:10px;letter-spacing:.05em}.swiss-note-panel{padding:16px clamp(18px,4vw,52px);border-bottom:1px solid var(--reader-line);background:var(--reader-bg)}.swiss-note-panel>div{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px;font-size:11px;letter-spacing:.08em}.swiss-note-panel textarea{display:block;width:100%;height:96px;resize:vertical;border:1px solid var(--reader-line);border-radius:0;padding:12px;background:var(--reader-bg);color:var(--reader-fg);font:14px/1.55 Arial,sans-serif;outline:none}.swiss-note-panel textarea:focus{border-color:var(--reader-fg)}.swiss-note-panel small{display:block;margin-top:6px;color:var(--reader-muted);font-size:9px}
.swiss-reader-hero{position:relative;padding:clamp(36px,7vw,88px) clamp(20px,7vw,92px) clamp(42px,8vw,96px);background:var(--reader-bg)}
.swiss-red-rule{width:72px;height:6px;background:var(--reader-accent);margin-bottom:34px}.swiss-meta{display:grid;grid-template-columns:90px 1fr auto;align-items:baseline;border-top:2px solid var(--reader-fg);padding-top:12px;font-size:11px;letter-spacing:.12em}.swiss-meta b{font-size:34px;line-height:1;color:var(--reader-accent)}.swiss-meta span:last-child{text-align:right}
.swiss-reader-hero h1{max-width:980px;margin:clamp(34px,7vw,78px) 0 0;font-size:clamp(38px,7vw,92px);font-weight:800;letter-spacing:-.055em;line-height:.98}
.swiss-cover{display:block;width:100%;max-height:72vh;object-fit:cover;border-radius:0}
.swiss-reader-body{width:min(760px,calc(100% - 40px));margin:0 auto;padding:clamp(42px,8vw,92px) 0 70px}.swiss-summary{margin:0 0 42px;font-size:var(--reader-summary-size);font-weight:500;line-height:1.45;letter-spacing:-.02em}.swiss-body-rule{width:72px;height:5px;background:var(--reader-accent);margin-bottom:42px}.swiss-reader-body>div>p{font-size:var(--reader-body-size)!important;line-height:1.9!important;margin:0 0 26px}.swiss-reader-body img{border-radius:0!important}.swiss-theme-eink .swiss-reader-body img,.swiss-theme-eink .swiss-cover{filter:grayscale(1) contrast(1.12)}
.richtext h2{margin:46px 0 18px;font-size:calc(var(--reader-body-size)*1.65);line-height:1.18;letter-spacing:-.03em}.richtext h3{margin:38px 0 15px;font-size:calc(var(--reader-body-size)*1.3);line-height:1.25}.richtext blockquote{margin:32px 0;padding:15px 20px;border-left:5px solid var(--reader-accent);background:color-mix(in srgb,var(--reader-fg) 5%,var(--reader-bg));font:italic var(--reader-body-size)/1.75 Georgia,serif}.richtext ul,.richtext ol{margin:22px 0;padding-left:26px}.richtext li{margin:8px 0;font-size:var(--reader-body-size);line-height:1.7}.richtext hr{border:0;border-top:1px solid var(--reader-line);margin:44px 0}.richtext a{color:var(--reader-accent);text-underline-offset:3px}.richtext figure{margin:30px 0}.richtext figcaption{margin-top:8px;color:var(--reader-muted);font-size:10px;letter-spacing:.04em}
.swiss-lock{position:absolute;left:0;right:0;bottom:0;display:flex;flex-direction:column;align-items:flex-start;padding:100px 0 8px;background:linear-gradient(180deg,transparent,var(--reader-bg) 48%)}.swiss-lock b{margin-top:12px;font-size:18px}.swiss-lock span{margin-top:7px;color:var(--reader-muted);font-size:13px}.swiss-lock button{margin-top:18px;border:0;border-radius:0;background:var(--reader-fg);color:var(--reader-bg);padding:13px 18px;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.06em}
.swiss-article-footer{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:start;gap:18px;margin-top:70px;padding-top:16px;border-top:2px solid var(--reader-fg);font-size:10px;letter-spacing:.08em}.swiss-article-footer img{display:block;width:auto;height:34px;max-width:150px;object-fit:contain;object-position:left center;filter:grayscale(1) brightness(0)}.swiss-theme-night .swiss-article-footer img{filter:grayscale(1) brightness(0) invert(1)}.swiss-theme-eink .swiss-article-footer img{filter:grayscale(1) brightness(0)!important}.swiss-footer-copy{min-width:0;display:flex;flex-direction:column;align-items:flex-start;gap:4px}.swiss-footer-title{font-weight:700;line-height:1.45;overflow-wrap:anywhere}.swiss-footer-site{white-space:nowrap;line-height:1.3;color:var(--reader-muted)}
@media (min-width:700px){
  .xart-stage{min-height:100dvh;padding:0;background:#FAF9F4;align-items:stretch}
  .xart-device{width:100%;height:100dvh;border:0;border-radius:0;box-shadow:none}
  .xart-device header,.xart-device main,.xart-device footer{padding-left:max(32px,env(safe-area-inset-left));padding-right:max(32px,env(safe-area-inset-right))}
  .xart-device main{scrollbar-gutter:stable}
}
@media (max-width:699px){.swiss-reader-header{grid-template-columns:1fr auto}.swiss-reader-brand{display:none}.swiss-reader-header>button span{display:none}.swiss-reader-toolbar{justify-content:flex-start;gap:8px;padding:7px 14px;overflow-x:auto}.swiss-tool-group{gap:3px;flex:0 0 auto}.swiss-tool-group button{padding:0 7px}.swiss-tool-actions{margin-left:0}.swiss-tool-actions button span{display:none}.swiss-meta{grid-template-columns:58px 1fr}.swiss-meta span:last-child{grid-column:2;text-align:left;margin-top:8px}.swiss-reader-hero h1{margin:38px 0 0}.swiss-reader-body{width:calc(100% - 40px)}.swiss-article-footer{gap:12px}.swiss-footer-copy{gap:1px}}
`;

export default function App(){
  if(location.pathname.startsWith("/admin"))return <Admin/>;
  const[tab,setTab]=useState("discover"),[open,setOpen]=useState(null),[subscribed,setSubscribed]=useState(false),[items,setItems]=useState(fallbackItems),[lang,setLang]=useState(()=>localStorage.getItem("xart-language")||"zh"),[showSplash,setShowSplash]=useState(true);
  useEffect(()=>{const timer=setTimeout(()=>setShowSplash(false),1800);return()=>clearTimeout(timer)},[]);
  useEffect(()=>{localStorage.setItem("xart-language",lang);document.documentElement.lang=lang==="zh"?"zh-CN":lang},[lang]);
  useEffect(()=>{
    let active=true;
    const syncArticles=()=>fetch(`/api/articles?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(active&&data.articles?.length)setItems(data.articles.map(p=>({id:p.id,n:p.n,tag:p.tag,minutes:p.minutes,locked:p.locked,language:p.language||"all",cover_image:p.cover_image||"",zh:[p.zh_title,p.zh_summary],fr:[p.fr_title,p.fr_summary],en:[p.en_title,p.en_summary],content:{zh:p.zh_content,fr:p.fr_content,en:p.en_content}})))}).catch(()=>{});
    const resume=()=>{if(document.visibilityState==="visible")syncArticles()};
    syncArticles();
    document.addEventListener("visibilitychange",resume);
    window.addEventListener("focus",syncArticles);
    window.addEventListener("pageshow",syncArticles);
    window.addEventListener("online",syncArticles);
    const timer=setInterval(()=>{if(document.visibilityState==="visible")syncArticles()},60000);
    return()=>{active=false;clearInterval(timer);document.removeEventListener("visibilitychange",resume);window.removeEventListener("focus",syncArticles);window.removeEventListener("pageshow",syncArticles);window.removeEventListener("online",syncArticles)};
  },[]);
  useEffect(()=>{
    let checking=false;
    const checkVersion=async()=>{if(checking||document.visibilityState!=="visible")return;checking=true;try{const response=await fetch(`/?app-version=${Date.now()}`,{cache:"no-store",headers:{"cache-control":"no-cache"}});if(!response.ok)return;const html=await response.text(),parsed=new DOMParser().parseFromString(html,"text/html"),latest=parsed.querySelector('script[type="module"][src]')?.getAttribute("src"),current=document.querySelector('script[type="module"][src]')?.getAttribute("src");if(latest&&current&&latest!==current){const next=new URL(location.href);next.searchParams.set("app-update",Date.now());location.replace(next.href)}}catch{}finally{checking=false}};
    const resume=()=>{if(document.visibilityState==="visible")checkVersion()};
    document.addEventListener("visibilitychange",resume);
    window.addEventListener("focus",checkVersion);
    window.addEventListener("pageshow",checkVersion);
    window.addEventListener("online",checkVersion);
    const timer=setInterval(checkVersion,300000);
    checkVersion();
    return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",resume);window.removeEventListener("focus",checkVersion);window.removeEventListener("pageshow",checkVersion);window.removeEventListener("online",checkVersion)};
  },[]);
  useEffect(()=>{const params=new URLSearchParams(location.search),sessionId=params.get("session_id")||localStorage.getItem("xart-stripe-session");if(params.get("checkout")==="cancelled")history.replaceState({},"",location.pathname);if(!sessionId)return;fetch(`/api/verify-checkout-session?session_id=${encodeURIComponent(sessionId)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(data=>{if(data.active){setSubscribed(true);localStorage.setItem("xart-stripe-session",sessionId)}else localStorage.removeItem("xart-stripe-session");if(params.get("session_id"))history.replaceState({},"",location.pathname)}).catch(()=>{})},[]);
  let screen=open?<Reader item={open} lang={lang} setLang={setLang} back={()=>setOpen(null)} toSubscribe={()=>{setOpen(null);setTab("subscribe")}} subscribed={subscribed}/>:tab==="discover"?<Discover lang={lang} setLang={setLang} open={setOpen} items={items}/>:tab==="subscribe"?<Subscribe lang={lang} setLang={setLang} subscribed={subscribed} onSubscribed={()=>setSubscribed(true)}/>:<Profile lang={lang} setLang={setLang} subscribed={subscribed} items={items} onRead={setOpen}/>;
  return <><style>{responsiveStyles}</style><div className="xart-stage w-full flex items-center justify-center"><div className="xart-device" style={{overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{flex:1,overflow:"hidden"}}>{screen}</div>{!open&&<Tabs tab={tab} setTab={setTab} lang={lang}/>}</div></div>{showSplash&&<div className="xart-splash" aria-label="X-ART Lab"><img src="/api/site-logo" alt="X-ART Lab"/></div>}</>
}
