const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store"}});
const authorized=(request,env)=>Boolean(env.ADMIN_TOKEN)&&request.headers.get("Authorization")===`Bearer ${env.ADMIN_TOKEN}`;
const clean=value=>String(value||"").replace(/[<>]/g,"").trim();
async function init(db){
  await db.prepare(`CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT NOT NULL UNIQUE,zh_name TEXT NOT NULL,fr_name TEXT NOT NULL,en_name TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  try{await db.prepare(`INSERT OR IGNORE INTO categories(slug,zh_name,fr_name,en_name,sort_order) SELECT DISTINCT tag,tag,tag,tag,100 FROM articles WHERE tag<>''`).run()}catch{}
}
export async function onRequestGet({request,env}){if(!authorized(request,env))return json({error:"Unauthorized"},401);if(!env.DB)return json({error:"Database unavailable"},503);await init(env.DB);const{results}=await env.DB.prepare(`SELECT c.*,COUNT(a.id) article_count FROM categories c LEFT JOIN articles a ON a.tag=c.slug GROUP BY c.id ORDER BY c.sort_order,c.id`).all();return json({categories:results})}
export async function onRequestPost({request,env}){if(!authorized(request,env))return json({error:"Unauthorized"},401);await init(env.DB);const body=await request.json(),slug=clean(body.slug||body.en_name||body.zh_name).slice(0,60);if(!slug)return json({error:"Name required"},400);const values=[slug,clean(body.zh_name||slug).slice(0,60),clean(body.fr_name||slug).slice(0,60),clean(body.en_name||slug).slice(0,60),Number(body.sort_order)||0];if(body.id){const old=await env.DB.prepare("SELECT slug FROM categories WHERE id=?").bind(Number(body.id)).first();await env.DB.prepare("UPDATE categories SET slug=?,zh_name=?,fr_name=?,en_name=?,sort_order=? WHERE id=?").bind(...values,Number(body.id)).run();if(old&&old.slug!==slug)await env.DB.prepare("UPDATE articles SET tag=? WHERE tag=?").bind(slug,old.slug).run();return json({ok:true})}await env.DB.prepare("INSERT INTO categories(slug,zh_name,fr_name,en_name,sort_order) VALUES(?,?,?,?,?)").bind(...values).run();return json({ok:true},201)}
export async function onRequestDelete({request,env}){if(!authorized(request,env))return json({error:"Unauthorized"},401);await init(env.DB);const id=Number(new URL(request.url).searchParams.get("id")),row=await env.DB.prepare(`SELECT c.id,COUNT(a.id) count FROM categories c LEFT JOIN articles a ON a.tag=c.slug WHERE c.id=? GROUP BY c.id`).bind(id).first();if(!row)return json({error:"Not found"},404);if(Number(row.count)>0)return json({error:"Only empty categories can be deleted"},409);await env.DB.prepare("DELETE FROM categories WHERE id=?").bind(id).run();return json({ok:true})}
